name: default

on:
  push:
  schedule:
    - cron: '12 8 * * *'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Renew
        run: |
          pip install -r requirements.txt
          python main.py
        env:
          PKU_USERNAME: ${{ secrets.PKU_USERNAME }}
          PKU_PASSWORD: ${{ secrets.PKU_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.json
